const functions = require("firebase-functions");
const { Timestamp } = require("firebase-admin/firestore");

// export to index.js like: exports.autoIncidentSimulator = autoIncidentSimulator(db, corsHandler)
module.exports = (db, corsHandler) =>
  functions.https.onRequest(async (req, res) => {
    corsHandler(req, res, async () => {
      try {
        const zones = ["Zone A", "Zone B", "Zone C"];
        const types = ["Fire", "Medical", "Security", "Panic"];
        const statuses = ["Ongoing", "Investigating"];

        const zone = zones[Math.floor(Math.random() * zones.length)];
        const type = types[Math.floor(Math.random() * types.length)];
        const status = statuses[Math.floor(Math.random() * statuses.length)];

        const incident = {
          zone,
          type,
          status,
          autoGenerated: true,
          timestamp: Timestamp.now(),
        };

        await db.collection("incidents").add(incident);

        console.log("Auto-incident created:", incident);
        res.status(200).send(`✅ Auto incident created in ${zone} (${type})`);
      } catch (err) {
        console.error("Auto incident error:", err);
        res.status(500).send("❌ Failed to create auto-incident.");
      }
    });
  });
